version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Web UI for Qdrant (development only)
  qdrant-dashboard:
    image: qdrant/qdrant-web-ui:latest
    ports:
      - "4000:80"
    environment:
      - QDRANT_API_URL=http://qdrant:6333
    depends_on:
      - qdrant
    profiles:
      - dev
